version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: person
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  web:
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
